Repository mojolicious/mojo, pull requests merged in 2019-07, with the labels that each got.

#1363 Add high level benefits to the README
  README.md
Labels: docs, vote

#1379 Validate negative integers
  lib/Mojolicious/Validator.pm
  t/mojolicious/validation_lite_app.t
Labels: feature, vote

#1380 add private packages to no_index metadata
  Makefile.PL
Labels: vote

#1393 Protect from undef values in Mojo::File objects
  lib/Mojo/File.pm
  t/mojo/file.t
Labels: vote

#1378 use re::is_regexp to detect regex refs
  lib/Mojo/Collection.pm
  lib/Mojolicious/Plugin/HeaderCondition.pm
Labels: vote

#1360 head and tail methods for Mojo::Collection
  lib/Mojo/Collection.pm
  t/mojo/collection.t
Labels: feature, vote
